/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.profil_saya;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.ImageIcon;
import koneksi.koneksi;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import spksukmajayabaru.UserSession;

/**
 *
 * @author Acer
 */
public class profil_saya extends javax.swing.JPanel {
    
    private Connection conne = new koneksi().getConnection();
    koneksi conn= new koneksi();

    /**
     * Creates new form profil_saya
     */
    public profil_saya() {
        initComponents();
         loadUserProfile();
         tampilData();
    }
    
    public void tampilData() {
        try {
            UserSession userSession = UserSession.getInstance();
            String userName = userSession.getUserName();
            int userId = userSession.getUserId();

            String getUser = "SELECT foto,nama,email,tanggal FROM tbl_user WHERE id='"+userId+"'";
            ResultSet res = conn.ambilData(getUser);

            String fotoPath = "";        
            String nama = "";
            String email = "";
            String tanggal = "";

            if (res.next()) {
                fotoPath = res.getString("foto");            
                nama = res.getString("nama");
                email = res.getString("email");
                tanggal = res.getString("tanggal");

                // Konversi tanggal
                SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal dari database
                SimpleDateFormat outputFormat = new SimpleDateFormat("EEEE, dd MMMM yyyy", new Locale("id", "ID")); // Format tanggal Indonesia
                Date date = inputFormat.parse(tanggal);
                String formattedDate = outputFormat.format(date);

                // Membuat ImageIcon dari path file
                ImageIcon imageIcon = new ImageIcon(fotoPath);
                jLabelTampilFoto.setIcon(imageIcon); // Set ikon ke JLabel
                jLabelTampilNama.setText(nama);            
                jLabelTampilEmail.setText(email);
                jLabelTampilTanggal.setText(formattedDate);
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Cetak stack trace untuk debug
        } catch (ParseException e) {
            e.printStackTrace(); // Cetak stack trace untuk debug
        }
    }


    
    private void loadUserProfile() {
        // Ambil data dari UserSession
        UserSession userSession = UserSession.getInstance();
        String userName = userSession.getUserName();
        int userId = userSession.getUserId();

        // Tampilkan informasi di UI
       System.out.println("ID: " + userId + "\nNama: " + userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTampilFoto = new javax.swing.JLabel();
        jLabelTampilNama = new javax.swing.JLabel();
        jLabelTampilEmail = new javax.swing.JLabel();
        jLabelTampilTanggal = new javax.swing.JLabel();
        jLabelIconNama = new javax.swing.JLabel();
        jLabelIconEmail = new javax.swing.JLabel();
        jLabelIconTanggal = new javax.swing.JLabel();
        jLabelTanggalInfo = new javax.swing.JLabel();
        jLabelCard = new javax.swing.JLabel();

        setLayout(null);

        jLabelTampilFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelTampilFoto);
        jLabelTampilFoto.setBounds(224, 212, 190, 210);

        jLabelTampilNama.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabelTampilNama.setForeground(new java.awt.Color(16, 184, 255));
        jLabelTampilNama.setText("Nama");
        add(jLabelTampilNama);
        jLabelTampilNama.setBounds(550, 230, 270, 50);

        jLabelTampilEmail.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabelTampilEmail.setForeground(new java.awt.Color(16, 184, 255));
        jLabelTampilEmail.setText("Email");
        add(jLabelTampilEmail);
        jLabelTampilEmail.setBounds(550, 290, 290, 50);

        jLabelTampilTanggal.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabelTampilTanggal.setForeground(new java.awt.Color(16, 184, 255));
        jLabelTampilTanggal.setText("Tanggal");
        add(jLabelTampilTanggal);
        jLabelTampilTanggal.setBounds(680, 360, 230, 40);

        jLabelIconNama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-profil.png"))); // NOI18N
        jLabelIconNama.setText("jLabel1");
        add(jLabelIconNama);
        jLabelIconNama.setBounds(480, 220, 50, 60);

        jLabelIconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gmail.png"))); // NOI18N
        jLabelIconEmail.setText("jLabel2");
        add(jLabelIconEmail);
        jLabelIconEmail.setBounds(480, 290, 50, 50);

        jLabelIconTanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jLabelIconTanggal.setText("jLabel3");
        add(jLabelIconTanggal);
        jLabelIconTanggal.setBounds(480, 350, 50, 60);

        jLabelTanggalInfo.setBackground(new java.awt.Color(16, 184, 255));
        jLabelTanggalInfo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabelTanggalInfo.setForeground(new java.awt.Color(16, 184, 255));
        jLabelTanggalInfo.setText("Bergabung Dari");
        add(jLabelTanggalInfo);
        jLabelTanggalInfo.setBounds(550, 360, 130, 40);

        jLabelCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card-profil-2.png"))); // NOI18N
        jLabelCard.setText("jLabel1");
        add(jLabelCard);
        jLabelCard.setBounds(40, 35, 1003, 591);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelIconEmail;
    private javax.swing.JLabel jLabelIconNama;
    private javax.swing.JLabel jLabelIconTanggal;
    private javax.swing.JLabel jLabelTampilEmail;
    private javax.swing.JLabel jLabelTampilFoto;
    private javax.swing.JLabel jLabelTampilNama;
    private javax.swing.JLabel jLabelTampilTanggal;
    private javax.swing.JLabel jLabelTanggalInfo;
    // End of variables declaration//GEN-END:variables
}
