/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.laporan;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer
 */
public class laporan extends javax.swing.JPanel {
    private Connection conne = new koneksi().getConnection();
    koneksi conn= new koneksi();
    /**
     * Creates new form dashboard
     */
    public laporan() {
        initComponents();
        
        setSize(1030, 630); // Ukuran panel sesuai kebutuhan
        setOpaque(false); 
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cetak_laporan_kriteria = new javax.swing.JButton();
        btn_cetak_laporan_nilai_penduduk = new javax.swing.JButton();
        btn_cetak_laporan_normalisasi = new javax.swing.JButton();
        btn_cetak_laporan_nilai_akhir = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1080, 690));
        setLayout(null);

        btn_cetak_laporan_kriteria.setBackground(new java.awt.Color(0, 204, 0));
        btn_cetak_laporan_kriteria.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btn_cetak_laporan_kriteria.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak_laporan_kriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-clipboard.png"))); // NOI18N
        btn_cetak_laporan_kriteria.setText("Cetak Laporan Data Nilai Kriteria");
        btn_cetak_laporan_kriteria.setToolTipText("Klik untuk mengupdate data.");
        btn_cetak_laporan_kriteria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_cetak_laporan_kriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_laporan_kriteriaActionPerformed(evt);
            }
        });
        add(btn_cetak_laporan_kriteria);
        btn_cetak_laporan_kriteria.setBounds(350, 230, 360, 70);

        btn_cetak_laporan_nilai_penduduk.setBackground(new java.awt.Color(0, 204, 0));
        btn_cetak_laporan_nilai_penduduk.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btn_cetak_laporan_nilai_penduduk.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak_laporan_nilai_penduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-clipboard.png"))); // NOI18N
        btn_cetak_laporan_nilai_penduduk.setText("Cetak Laporan Data Nilai Penduduk");
        btn_cetak_laporan_nilai_penduduk.setToolTipText("Klik untuk mengupdate data.");
        btn_cetak_laporan_nilai_penduduk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_cetak_laporan_nilai_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_laporan_nilai_pendudukActionPerformed(evt);
            }
        });
        add(btn_cetak_laporan_nilai_penduduk);
        btn_cetak_laporan_nilai_penduduk.setBounds(350, 140, 360, 70);

        btn_cetak_laporan_normalisasi.setBackground(new java.awt.Color(0, 204, 0));
        btn_cetak_laporan_normalisasi.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btn_cetak_laporan_normalisasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak_laporan_normalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-clipboard.png"))); // NOI18N
        btn_cetak_laporan_normalisasi.setText("Cetak Laporan Data Normalisasi");
        btn_cetak_laporan_normalisasi.setToolTipText("Klik untuk mengupdate data.");
        btn_cetak_laporan_normalisasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_cetak_laporan_normalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_laporan_normalisasiActionPerformed(evt);
            }
        });
        add(btn_cetak_laporan_normalisasi);
        btn_cetak_laporan_normalisasi.setBounds(350, 320, 360, 70);

        btn_cetak_laporan_nilai_akhir.setBackground(new java.awt.Color(0, 204, 0));
        btn_cetak_laporan_nilai_akhir.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btn_cetak_laporan_nilai_akhir.setForeground(new java.awt.Color(255, 255, 255));
        btn_cetak_laporan_nilai_akhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-clipboard.png"))); // NOI18N
        btn_cetak_laporan_nilai_akhir.setText("Cetak Laporan Data Nilai Hasil Akhir");
        btn_cetak_laporan_nilai_akhir.setToolTipText("Klik untuk mengupdate data.");
        btn_cetak_laporan_nilai_akhir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_cetak_laporan_nilai_akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_laporan_nilai_akhirActionPerformed(evt);
            }
        });
        add(btn_cetak_laporan_nilai_akhir);
        btn_cetak_laporan_nilai_akhir.setBounds(350, 410, 360, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetak_laporan_kriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_laporan_kriteriaActionPerformed
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/menu/laporan/kriteriareport.jasper", null, conne);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cetak_laporan_kriteriaActionPerformed

    private void btn_cetak_laporan_nilai_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_laporan_nilai_pendudukActionPerformed
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/menu/laporan/nilaidatapenduduk.jasper", null, conne);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cetak_laporan_nilai_pendudukActionPerformed

    private void btn_cetak_laporan_normalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_laporan_normalisasiActionPerformed
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/menu/laporan/normalisasireport.jasper", null, conne);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cetak_laporan_normalisasiActionPerformed

    private void btn_cetak_laporan_nilai_akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_laporan_nilai_akhirActionPerformed
        try {
            JasperPrint jp = JasperFillManager.fillReport("src/menu/laporan/reportnilaiakhir.jasper", null, conne);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cetak_laporan_nilai_akhirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak_laporan_kriteria;
    private javax.swing.JButton btn_cetak_laporan_nilai_akhir;
    private javax.swing.JButton btn_cetak_laporan_nilai_penduduk;
    private javax.swing.JButton btn_cetak_laporan_normalisasi;
    // End of variables declaration//GEN-END:variables
}
